### ISSUE TITLE
1.19.4 mod compatibility issue <have not tested or verified for other versions>

### ISSUE THREAD

**Issue by crazysmile11012** [negative-light-media/soulsiphon#35]
**Describe the bug**
When Minecraft is run with soulsiphon it runs nominaly, however when you run it with other Mods it throws a fatal error:
![image](https://github.com/negative-light-media/soulsiphon/assets/107813207/04d9aa84-d5e0-4e89-a1bf-8e9a18d4b83c)

**To Reproduce**
1. Get the Jar for soulsiphon using your favorite method eg: modrinth, curseforge, github
2. Drop it in your games "mods" folder
3. Make sure you have other mods in there  (in my case its crazymodplus)
4. The game should(not) crash to desktop

**Expected behavior**
It should Run with any mod that does not 
- share modid
- share itemnames
- share blocknames
- esc....
this is unintended behavior 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 version 22H2
 - Browser Opera/ chromium
 - Version forge 1.19.4 

**Additional context**
the logfile:
[latest.log](https://github.com/negative-light-media/soulsiphon/files/14201755/latest.log)

This error would be serious because the mod would not work in modpacks greatly reducing our reach

**Comment by crazysmile11012** [comment]
@Negative-light

**Comment by Negative-light** [comment]
This is caused by the move to the multiloader.
Since that move 1.20.x and on are the only supported versions. I will make sure a update gets added to the README
