### ISSUE TITLE
Easter Eggs (!!! Spoilers Ahead !!!)

### ISSUE THREAD

**Issue by Healex2** [negative-light-media/soulsiphon#5]
The following Interactions are the result of "Using" a Weeping Urn on the listed entities. In addition the the results listed below, the Weeping Urn is emptied, becoming an Empty Weeping Urn: 
Zombie -> Nitwit Villager
Baby Zombie -> Baby Nitwit Villager
Wither (Boss) -> Heals the Wither

**Comment by crazysmile11012** [comment]
rose -> wither rose
any woodtype -> warped woodtype equivalent

**Comment by Negative-light** [comment]
So as far as the Zombie stuff could we have then just convert to regular villagers I think that would work easily.

**Comment by Negative-light** [comment]
closed on accedent

**Comment by Healex2** [comment]
> So as far as the Zombie stuff could we have then just convert to regular villagers I think that would work easily.

I wanted nitwits because, while they have souls, they have no brains. Also, that should just be some extra nbt, no?
`_ _ _ _ _`

> rose -> wither rose any woodtype -> warped woodtype equivalent

Sell me on the wither rose one, because I'm not convinced that's not too op. 
As for the woods, I don't really see that one.

**Comment by Negative-light** [comment]
> > So as far as the Zombie stuff could we have then just convert to regular villagers I think that would work easily.
> 
> I wanted nitwits because, while they have souls, they have no brains. Also, that should just be some extra nbt, no?

Hurm I will have to see about getting the data of a villager I guess.

---

- [ ] Add entitiy detection to the weeping urn item
- [ ] Add detection specific to zombie
- [ ] Add function that starts the cure effect for the zombie
-

**Comment by Negative-light** [comment]
I have picked this one back up please ignore previous content. But this guy is in progress
