### ISSUE TITLE
Create Readme

### ISSUE THREAD

**Issue by Negative-light** [negative-light-media/soulsiphon#6]
Writeup a Read ME file to put as the main page

**Comment by Healex2** [comment]
Draft:
> Welcome to Soul Siphon, a vanilla-like mod that builds on the lore of Sculk blocks and the Nether's soul-based materials. 

> The core idea is that the Soul Siphon item is used to extract the souls out of Soul Sand and Soul Soil, leaving behind untainted Sand or Red Sand, respectively. If a suitable block is below the Soul Siphon when the souls are extracted from the Soul Sand/Soil, then the souls can be re-used for crafting other materials.

**Comment by Negative-light** [comment]
Although the README has been updated this issues has been resolved
